# Generated by Django 5.0 on 2024-07-14 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userx',
            name='some_field',
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_in_store', to='adc.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='adc.store')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adc.item')),
                ('sold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='adc.solditem')),
            ],
        ),
    ]
