# Generated by Django 5.0 on 2024-07-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0003_supplier_remove_solditementry_sold_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_number',
        ),
    ]
