# Generated by Django 5.0 on 2024-07-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0009_alter_customer_stores_alter_employee_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stores',
        ),
        migrations.AddField(
            model_name='category',
            name='stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adc.store'),
        ),
    ]
