# Generated by Django 5.0 on 2024-07-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0010_remove_category_stores_category_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='adc.store'),
        ),
    ]
