# Generated by Django 5.0 on 2024-07-20 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0012_remove_transactionproduct_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='store',
        ),
        migrations.RemoveField(
            model_name='category',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='stores',
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='adc.store'),
        ),
        migrations.AddField(
            model_name='category',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='categories', to='adc.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adc.category'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adc.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerTransaction',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
