# Generated by Django 5.0 on 2024-07-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0015_product_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliertransaction',
            old_name='amount_paid',
            new_name='total_amount_paid',
        ),
        migrations.RenameField(
            model_name='transactionproduct',
            old_name='price_per_unit',
            new_name='price',
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='extra_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='shipment_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
