# Generated by Django 5.0 on 2024-07-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0018_rename_total_price_bill_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='supplier',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='adc.store'),
        ),
    ]
