# Generated by Django 5.0 on 2024-07-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0019_remove_store_suppliers_supplier_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionproduct',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('PKT', 'Packet'), ('Bunch', 'Bunch')], default='KG', max_length=10),
        ),
    ]
