# Generated by Django 5.0 on 2024-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0020_transactionproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
