# Generated by Django 5.0 on 2024-07-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0022_alter_suppliertransaction_total_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adc.store'),
        ),
        migrations.AddField(
            model_name='transactionproduct',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adc.store'),
        ),
    ]
