# Generated by Django 5.0 on 2024-07-25 06:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0023_suppliertransaction_store_transactionproduct_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adc.store'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('PKT', 'Packet'), ('Bunch', 'Bunch')], default='KG', max_length=10),
        ),
    ]
