# Generated by Django 5.0 on 2024-07-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0025_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
