# Generated by Django 5.0 on 2024-07-26 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0026_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('petrol', 'Petrol'), ('rent', 'Rent'), ('electricity', 'Electricity'), ('water', 'Water'), ('equipment', 'Equipment'), ('facility', 'Facility'), ('car', 'Car'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='adc.employee')),
            ],
        ),
    ]
