# Generated by Django 5.0 on 2024-08-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0029_salarychange_change_type_alter_salarychange_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarychange',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_salary_changes', to='adc.employee'),
        ),
    ]
