# Generated by Django 5.0 on 2024-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0032_remove_supplier_store_supplier_stores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='stores',
            new_name='store',
        ),
    ]
