# Generated by Django 5.0 on 2024-08-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adc', '0034_alter_supplier_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='adc.store'),
        ),
    ]
